name: Codeflash

on:
  pull_request:
    paths:
      # So that this workflow only runs when code within the target module is modified
      - {{ codeflash_module_path }}
  workflow_dispatch:

concurrency:
  # Any new push to the PR will cancel the previous run, so that only the latest code is optimized
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  optimize:
    name: Optimize new code in this PR
    # Don't run codeflash on codeflash-ai[bot] commits, prevent duplicate optimizations
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      # TODO: Replace the following with your project's python installation method
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {{ python_version }}
      # TODO: Replace the following with your project's dependency installation method
      - name: Install Project Dependencies
      # TODO: Replace the following with your project setup method (e.g. poetry, pip) to install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codeflash
      - name: Run Codeflash to optimize code
        id: optimize_code
        run: |
          codeflash
