name: Coverage E2E

on:
  pull_request:
  workflow_dispatch:

jobs:
  end-to-end-test-coverage:
    runs-on: ubuntu-latest
    env:
      CODEFLASH_AIS_SERVER: prod
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      MAX_RETRIES: 3
      RETRY_DELAY: 5
      CODEFLASH_END_TO_END: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11 for CLI
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11.6

      - name: Run Codeflash to optimize code
        id: optimize_code
        run: |
          uv run --with black -p 3.11 python tests/scripts/end_to_end_test_coverage.py