name: Mypy Type Checking for CLI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  type-check-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run mypy on allowlist
        run: uv run --all-groups mypy --non-interactive --config-file pyproject.toml @mypy_allowlist.txt
